# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  message:

    runs-on: ubuntu-latest

    #strategy:
    #  matrix:
    #    node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    #steps:
    #- uses: actions/checkout@v3
    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #    cache: 'npm'
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    
    steps:
        - uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            author_name: Integration Test # default: 8398a7@action-slack
            fields: repo,commit,message,author # default: repo,commit
            mention: here
            if_mention: failure,cancelled
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          if: always()
